modules/system/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import ProfileUpdateView, ProfileDetailView, UserRegisterView, UserLoginView, UserPasswordChangeView, \
    UserForgotPasswordView, UserPasswordResetConfirmView, EmailConfirmationSentView, UserConfirmEmailView, \
    EmailConfirmedView, EmailConfirmationFailedView, FeedbackCreateView

app_name = 'modules.system'

urlpatterns = [
    path('user/edit/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('user/<str:slug>/', ProfileDetailView.as_view(), name='profile_detail'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),
    path('feedback/', FeedbackCreateView.as_view(), name='feedback'),
]

real_estate_agency/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.defaults import page_not_found


# from realtor.views import index


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('captcha/', include('captcha.urls')),
    re_path(r'^chaining/', include('smart_selects.urls')),
    # path('', index, name='home'),
    path('', include('realtor.urls', namespace='realtor')),
    path('users/', include('modules.system.urls', namespace='system')),
]

from .settings import DEBUG, MEDIA_URL, MEDIA_ROOT
if DEBUG:
    # add debug toolbar only for DEBUG mode
    # urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

    # for show media files in DEBUG mode
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)


# handler404 = page_not_found
handler403 = 'modules.system.views.my_handler403'
handler404 = 'modules.system.views.my_handler404'
handler500 = 'modules.system.views.my_handler500'

# Настройка админ панели
admin.site.site_header = 'Панель администрирования сайта'
admin.site.index_title = 'Риэлтор'

realtor/urls.py
from django.urls import path, include

from .views import index, EstateCreateView, ShowEstate, EstatesList, EstateCreateView2

app_name = 'realtor'


urlpatterns = [
    # path('', index, name='home'),
    path('', EstatesList.as_view(), name='home'),
    path('create/', EstateCreateView.as_view(), name='create'),
    path('create2/', EstateCreateView2.as_view(), name='create2'),
    path('estate/<slug:estate_slug>/', ShowEstate.as_view(), name='estate'),
]

realtor/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.migrations.operations.base import Operation
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models import UniqueConstraint
from django.urls import reverse
from django.contrib.auth import get_user_model
from smart_selects.db_fields import ChainedForeignKey

# --------------------------------------------
# CATEGORY_CHOICES = (
#     (1, 'Жилая'),
#     (2, 'Коммерческая'),
# )
#
# TYPE_CHOICES = (
#     (1, 'Квартира'),
#     (2, 'Дом'),
#     (3, 'Участок'),
#     (11, 'Офисная'),
#     (12, 'Торговая'),
#     (13, 'Складская'),
#     (14, 'Производственная'),
#     (15, 'Прочая'),
# )

BATHROOM_CHOICES = (
    (1, 'Раздельный'),
    (2, 'Совмещенный'),
    (3, 'Общий'),
    (4, 'На улице'),
)

STATUS_CHOICES = (
    (1, 'Черновик'),
    (2, 'Опубликовано'),
    (3, 'Процесс сделки'),
    (4, 'Продано'),
    (5, 'Снято с публикации'),
)

OPERATION_CHOICES = (
    (1, 'Продажа'),
    (2, 'Аренда'),
)

class Estate(models.Model):
    """ объекты недвижимости """
    name = models.CharField(max_length=30, verbose_name='Заголовок')
    # category = models.IntegerField(choices=CATEGORY_CHOICES, null=True, verbose_name='Категория')
    # type = models.IntegerField(choices=TYPE_CHOICES, null=True, verbose_name='Тип')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, related_name='categories', verbose_name='Категория')
    type = ChainedForeignKey(
        'Type',  # Модель, с которой связано поле
        chained_field="category",  # Поле, от которого зависит выбор
        chained_model_field="category_id",  # Поле в модели Type, связанное с chained_field
        show_all=False,  # Показывать только связанные значения
        auto_choose=True,  # Автоматически выбирать значение, если оно единственное
        on_delete=models.PROTECT,
        related_name='types',
        verbose_name='Тип недвижимости'
    )
    operation = models.IntegerField(choices=OPERATION_CHOICES, verbose_name='Операция')
    status = models.IntegerField(choices=STATUS_CHOICES, default=1, verbose_name='Статус объекта')
    description = models.TextField(verbose_name='Описание')
    floor = models.IntegerField(blank=True, default=None, null=True, verbose_name='Этаж')
    number_rooms = models.IntegerField(blank=True, default=None, null=True, verbose_name='Количество комнат')
    number_floors = models.IntegerField(blank=True, default=None, null=True, verbose_name='Этажность дома')
    total_area = models.FloatField(blank=True, default=None, null=True, verbose_name='Общая площадь')
    living_area = models.FloatField(blank=True, default=None, null=True, verbose_name='Жилая площадь')
    kitchen_area = models.FloatField(blank=True, default=None, null=True, verbose_name='Площадь кухни')
    bathroom = models.IntegerField(blank=True, choices=BATHROOM_CHOICES, null=True, verbose_name='Санузел')
    city = models.ForeignKey('City', on_delete=models.PROTECT, related_name='cities', verbose_name='Город')
    district = ChainedForeignKey(
        'District',  # Модель, с которой связано поле
        chained_field="city",  # Поле, от которого зависит выбор
        chained_model_field="city_id",  # Поле в модели District, связанное с chained_field
        show_all=False,  # Показывать только связанные значения
        auto_choose=True,  # Автоматически выбирать значение, если оно единственное
        null=True,
        blank=True,
        on_delete=models.PROTECT,
        related_name='districts',
        verbose_name='Район'
    )
    street = models.CharField(blank=True, max_length=30, verbose_name='Улица')
    house = models.CharField(blank=True, max_length=10, verbose_name='Номер дома')
    apartment = models.CharField(blank=True, max_length=10, verbose_name='Номер квартиры')
    landmarks = models.CharField(blank=True, max_length=100, verbose_name='Ориентиры')
    owner_name = models.CharField(blank=True, max_length=30, verbose_name='Собственник (имя)')
    phone1 = PhoneNumberField(region='RU',blank=True, null=True, verbose_name='Телефон 1')
    # phone1 = models.CharField(blank=True, max_length=11, verbose_name='Телефон 1')
    phone2 = models.CharField(blank=True, max_length=11, verbose_name='Телефон 2')
    phone3 = models.CharField(blank=True, max_length=11, verbose_name='Телефон 3')
    telegram = models.CharField(blank=True, max_length=30, verbose_name='Телеграм')
    vk = models.CharField(blank=True, max_length=50, verbose_name='Страница ВК')
    creator = models.ForeignKey(get_user_model(), blank=True, null=True, on_delete=models.SET_NULL, related_name='creators', verbose_name='Создал запись')
    modifier = models.ForeignKey(get_user_model(), blank=True, null=True, on_delete=models.SET_NULL, related_name='modifiers', verbose_name='Изменил запись')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')
    slug = models.SlugField(unique=True, db_index=True, verbose_name='Slug')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Объект недвижимости"
        verbose_name_plural = "Объекты недвижимости"
        ordering = ['time_create']
        # indexes = [models.Index(fields=['time_create'])]

    # def save(self, *args, **kwargs):
    #     if not self.creator_id:  # Если поле user не заполнено
    #         self.creator = get_current_user()  # Заполняем текущим пользователем
    #     super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('realtor:estate', kwargs={'estate_slug': self.slug})


class Category(models.Model):
    """ справочник категорий недвижимости """
    name = models.CharField(unique=True, max_length=20, verbose_name='Категрия')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категрия недвижимости"
        verbose_name_plural = "Категрии недвижимости"


class Type(models.Model):
    """ справочник типов недвижимости """
    name = models.CharField(max_length=30, verbose_name='Тип')
    category_id = models.ForeignKey('Category', null=True, on_delete=models.CASCADE, related_name='categories_id', verbose_name='Категрия')
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тип недвижимости"
        verbose_name_plural = "Типы недвижимости"
        constraints = [
            UniqueConstraint(
                fields=['name', 'category_id'],  # Уникальное сочетание name и category_id
                name='unique_name_category'  # Имя ограничения
            )
        ]


class City(models.Model):
    """ справочник городов """
    name = models.CharField(unique=True, max_length=20, verbose_name='Город')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Город"
        verbose_name_plural = "Города"


class District(models.Model):
    """ справочник районов городов """
    name = models.CharField(max_length=30, verbose_name='Район')
    city_id = models.ForeignKey('City', null=True, on_delete=models.CASCADE, related_name='cities_id', verbose_name='Город')
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Район"
        verbose_name_plural = "Районы"
        constraints = [
            UniqueConstraint(
                fields=['name', 'city_id'],  # Уникальное сочетание name и city_id
                name='unique_name_city'  # Имя ограничения
            )
        ]


class EstateImage(models.Model):
    """ Изображения """
    estate = models.ForeignKey('Estate', related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/estates/')

    def __str__(self):
        return f"Image for {self.estate.name}"

    class Meta:
        verbose_name = "Фото объекта"
        verbose_name_plural = "Фото объекта"

realtor/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.utils.deconstruct import deconstructible
from multiupload.fields import MultiFileField
from phonenumber_field.formfields import PhoneNumberField

from .models import Estate, EstateImage


# @deconstructible
# class RussianValidator:
#     ALLOWED_CHARS = "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯабвгдеёжзийклмнопрстуфхцчшщбыъэюя0123456789- "
#     code = 'russian'
#
#     def __init__(self, message=None):
#         self.message = message if message else "Должны присутствовать только русские символы, дефис и пробел."
#
#     def __call__(self, value, *args, **kwargs):
#         if not (set(value) <= set(self.ALLOWED_CHARS)):
#             raise ValidationError(self.message, code=self.code)


class EstateCreateForm(forms.ModelForm):
    images = MultiFileField(min_num=1, max_num=10, max_file_size=1024 * 1024 * 5)  # До 10 файлов, каждый до 5 МБ

    class Meta:
        model = Estate
        phone1 = PhoneNumberField(widget=forms.TextInput(attrs={'placeholder': ('Phone')}), required=False)
        widgets = {
            'phone2': forms.TextInput(attrs={"class": "form-phone-input",
                                             'type': 'tel',
                                             'placeholder':"X (XXX) XXX-XX-XX",
                                             'pattern':"[0-9]\s?[\(]{0,1}9[0-9]{2}[\)]{0,1}\s?\d{3}[-]{0,1}\d{2}[-]{0,1}\d{2}",
                                             'autocomplete': "tel"}),
            'phone3': forms.TextInput(attrs={"class": "form-phone-input",
                                             'type': 'tel',
                                             'placeholder': "X (XXX) XXX-XX-XX",
                                             'pattern': "[0-9]\s?[\(]{0,1}9[0-9]{2}[\)]{0,1}\s?\d{3}[-]{0,1}\d{2}[-]{0,1}\d{2}",
                                             'autocomplete': "tel"}),
        }
        fields = '__all__'

        # < input
        # type = "tel"
        # id = "phone"
        # name = "phone"
        # placeholder = "+7 (XXX) XXX-XX-XX"
        # autocomplete = "tel"
        # required >
        # fields = [
        #     'name',
        #     'category',
        #     'type',
        #     'operation',
        #     'status',
        #     'description',
        #     'floor',
        #     'number_rooms',
        #     'number_floors',
        #     'total_area',
        #     'living_area',
        #     'kitchen_area',
        #     'bathroom',
        #     'city',
        #     'district',
        #     'street',
        #     'house',
        #     'apartment',
        #     'landmarks',
        #     'owner_name',
        #     'phone1',
        #     'phone2',
        #     'phone3',
        #     'telegram',
        #     'vk',
        #     'slug',
        #     'images',
        # ]
        # widgets = {
        #     'title': forms.TextInput(attrs={'class': 'form-input'}),
        #     'content': forms.Textarea(attrs={'cols': 50, 'rows': 5}),
        # }
        # labels = {'slug': 'URL'}

    # def clean_title(self):
    #     title = self.cleaned_data['title']
    #     if len(title) > 50:
    #         raise ValidationError("Длина превышает 50 символов")
    #
    #     return title


# class UploadFileForm(forms.Form):
#     file = forms.ImageField(label="Файл")

realtor/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, ListView

from .forms import EstateCreateForm
from .models import Estate


def index(request):
    return render(request, 'realtor/home.html', context={'title': 'Риелтор - Главная',})

# PermissionRequiredMixin, LoginRequiredMixin, DataMixin, CreateView
class EstateCreateView(CreateView):
    form_class = EstateCreateForm
    template_name = 'realtor/create.html'
    title_page = 'Добавление объекта недвижимсоти'
    permission_required = 'realtor.create_estate' # <приложение>.<действие>_<таблица>
    extra_context = {
        'title': 'Добавление объекта',
    }

    def form_valid(self, form):
        estate = form.save(commit=False)
        if not estate.creator:
            estate.creator = self.request.user
        estate.modifier = self.request.user
        return super().form_valid(form)


class EstateCreateView2(CreateView):
    model = Estate
    fields = '__all__'
    template_name = 'realtor/create2.html'
    success_url = reverse_lazy('realtor:home')
    extra_context = {
        'title': 'Добавление объекта',
    }


class ShowEstate(DetailView):
    model = Estate
    template_name = 'realtor/estate.html'
    slug_url_kwarg = 'estate_slug'
    context_object_name = 'estate'


class EstatesList(LoginRequiredMixin, ListView):
    model = Estate
    template_name = 'realtor/home.html'
    context_object_name = 'estates'
    extra_context = {
        'title': 'Риэлтор - Главная страница',
        # 'styles': 'tasks/css/styles.css',
    }

realtor/templates/realtor/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    {% if title %}
      <title>{{ title }}</title>
    {% else %}
      <title>Без заголовка</title>
    {% endif %}
    <link href="{% static 'realtor/css/styles.css' %}" type="text/css" rel="stylesheet">
</head>
<body>
    {% include './header.html' %}
    {% block content %}{% endblock %}
    {% block script %}{% endblock %}
</body>
</html>

realtor/templates/realtor/create.html
{% extends './base.html' %}
{% load static %}
{% block content %}
<div class="form-title">{{title}}</div>
<div class="form-wrapper">
    <form method="post" enctype="multipart/form-data" class="form-box">
        {% csrf_token %}

        <div class="form-group">
            <div class="form-char">
                <label for="{{ form.name.id_for_label }}" class="form-label">{{ form.name.label }}</label>
                {{ form.name }}
            </div>
            <div class="form-list">
                <label for="{{ form.operation.id_for_label }}" class="form-label">{{ form.operation.label }}</label>
                {{ form.operation }}
            </div>
            <div class="form-list">
                <label for="{{ form.category.id_for_label }}" class="form-label">{{ form.category.label }}</label>
                {{ form.category }}
            </div>
            <div class="form-list">
                <label for="{{ form.type.id_for_label }}" class="form-label">{{ form.type.label }}</label>
                {{ form.type }}
            </div> 
        </div>

        <div class="form-group">
            <div class="form-list">
                <label for="{{ form.city.id_for_label }}" class="form-label">{{ form.city.label }}</label>
                {{ form.city }}
            </div>
            <div class="form-list">
                <label for="{{ form.district.id_for_label }}" class="form-label">{{ form.district.label }}</label>
                {{ form.district }}
            </div>
            <div class="form-char">
                <label for="{{ form.landmarks.id_for_label }}" class="form-label">{{ form.landmarks.label }}</label>
                {{ form.landmarks }}
            </div>            
            <div class="form-char">
                <label for="{{ form.street.id_for_label }}" class="form-label">{{ form.street.label }}</label>
                {{ form.street }}
            </div>
            <div class="form-number">
                <label for="{{ form.house.id_for_label }}" class="form-label">{{ form.house.label }}</label>
                {{ form.house }}
            </div>
            <div class="form-number">
                <label for="{{ form.apartment.id_for_label }}" class="form-label">{{ form.apartment.label }}</label>
                {{ form.apartment }}
            </div>
        </div>

        <div class="form-group">
            <div class="form-number">
                <label for="{{ form.number_floors.id_for_label }}" class="form-label">{{ form.number_floors.label }}</label>
                {{ form.number_floors }}
            </div>
            <div class="form-number">
                <label for="{{ form.floor.id_for_label }}" class="form-label">{{ form.floor.label }}</label>
                {{ form.floor }}
            </div>
            <div class="form-number">
                <label for="{{ form.number_rooms.id_for_label }}" class="form-label">{{ form.number_rooms.label }}</label>
                {{ form.number_rooms }}
            </div>
            <div class="form-number">
                <label for="{{ form.total_area.id_for_label }}" class="form-label">{{ form.total_area.label }}, м<sup>2</sup></label>
                {{ form.total_area }}
            </div>
            <div class="form-number">
                <label for="{{ form.living_area.id_for_label }}" class="form-label">{{ form.living_area.label }}, м<sup>2</sup></label>
                {{ form.living_area }}
            </div>
            <div class="form-number">
                <label for="{{ form.kitchen_area.id_for_label }}" class="form-label">{{ form.kitchen_area.label }}, м<sup>2</sup></label>
                {{ form.kitchen_area }}
            </div>
            <div class="form-list">
                <label for="{{ form.bathroom.id_for_label }}" class="form-label">{{ form.bathroom.label }}</label>
                {{ form.bathroom }}
            </div>
        </div>

        <div class="form-group">
            <div class="form-text">
                <label for="{{ form.description.id_for_label }}" class="form-label">{{ form.description.label }}</label>
                <div>{{ form.description }}</div>
            </div>
        </div>
        
        <div class="form-group">
            <div class="form-char">
                <label for="{{ form.owner_name.id_for_label }}" class="form-label">{{ form.owner_name.label }}</label>
                {{ form.owner_name }}
            </div>
            <div class="form-char">
                <label for="{{ form.phone1.id_for_label }}" class="form-label">{{ form.phone1.label }}</label>
                {{ form.phone1 }}
            </div>
            <div class="form-char">
                <label for="{{ form.phone2.id_for_label }}" class="form-label">{{ form.phone2.label }}</label>
                {{ form.phone2 }}
            </div>
            <div class="form-char">
                <label for="{{ form.phone3.id_for_label }}" class="form-label">{{ form.phone3.label }}</label>
                {{ form.phone3 }}
            </div>
            <div class="form-char">
                <label for="{{ form.telegram.id_for_label }}" class="form-label">{{ form.telegram.label }}</label>
                {{ form.telegram }}
            </div>
            <div class="form-char">
                <label for="{{ form.vk.id_for_label }}" class="form-label">{{ form.vk.label }}</label>
                {{ form.vk }}
            </div>
        </div>


        <div class="form-list">
            <label for="{{ form.status.id_for_label }}" class="form-label">{{ form.status.label }}</label>
            {{ form.status }}
        </div>
    </form>

    <div class="form-submit-box">
        <button type="submit" class="form-submit-button">Сохранить объект</button>
    </div>
</div>

{% endblock %}

{% block script %}
    <script src="{% static 'realtor/js/form.js' %}"></script>
{% endblock %}


<!--    #       'name',
        #       'category',
        #       'type',
        #       'operation',
        #       'status',
        #       'description',
        #       'floor',
        #       'number_rooms',
        #       'number_floors',
        #       'total_area',
        #       'living_area',
        #       'kitchen_area',
        #     'bathroom',
        #       'city',
        #       'district',
        #       'street',
        #       'house',
        #       'apartment',
        #       'landmarks',

            #     'owner_name',
            #     'phone1',
            #     'phone2',
            #     'phone3',
            #     'telegram',
            #     'vk',
        #     'slug',
        #     'images',
-->

realtor/templates/realtor/create2.html
{% extends './base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <p><button type="submit">Отправить</button></p>
</form>
{% endblock %}

realtor/templates/realtor/estate.html
{% extends './base.html' %}

{% block content %}
<h1>{{estate.name}}</h1>
<p>{{estate.creator}}</p>
<p>{{estate.time_create}}</p>
<br/>
<p>{{estate.modifier}}</p>
<p>{{estate.time_update}}</p>
{% endblock %}

realtor/templates/realtor/header.html
{% load static %}
<header>
  <div class="header">
    <div class="header-outer">
      <a href="{% url 'realtor:home' %}" class="logo-link">
        <img src="{% static 'realtor/img/logo.jpg' %}"/>
      </a>
      <div class="header-block">
        <div class="header-up">
          <div class="header-info">
            <a class="header-phone" href="tel:+7(123)456-78-01">+7(123)456-78-01</a>
            <a class="header-phone" href="tel:+7(123)456-78-02">+7(123)456-78-02</a>
            <div class="header-text">Нужна квартира - звоните нам!</div>
          </div>
          <form class="header-search" role="search">
            <input type="search" class="form-control" placeholder="Поиск..." aria-label="Search">
          </form>
        </div>
        <div class="header-menu">
          <a href="{% url 'realtor:home' %}" class="header-menu-item-link">Главная</a>
          <a href="{% url 'realtor:create' %}" class="header-menu-item-link">Создать</a>
          <a href="{% url 'admin:index' %}" class="nav-link header-menu-item-link">Админка</a>
          <a href="{% url 'system:feedback' %}" class="nav-link header-menu-item-link">Обратная связь</a>
        </div>
      </div>
    </div>


<!--    <div class="text-end">-->
<!--      {% if user.is_authenticated %}-->
<!--      <a class="btn btn-success" href="{% url 'system:profile_detail' slug=user.profile.slug %}" role="button">{{user.username}}</a>-->
<!--      <form style="display:inline-block" method="post" action="{% url 'system:logout' %}">{% csrf_token %}<button class="btn btn-danger" type="submit">Выход</button></form>-->
<!--      {% else %}-->
<!--      <a class="btn btn-light text-dark me-2" href="{% url 'system:login' %}" role="button">Войти</a>-->
<!--      <a class="btn btn-primary" href="{% url 'system:register' %}" role="button">Регистрация</a>-->
<!--      {% endif %}-->
<!--    </div>-->
  </div>
</header>

realtor/templates/realtor/home.html
{% extends './base.html' %}

{% block content %}
<h1>Главная страница Риелтор</h1>
<hr />
{% for estate in estates %}
    <h1>{{estate.name}}</h1>
    <p>{{estate.creator}}</p>
    <p>{{estate.time_create}}</p>
    <a class="title" href="{{ estate.get_absolute_url }}">{{ estate.name }}</a>
    <br/>
    <p>{{estate.modifier}}</p>
    <p>{{estate.time_update}}</p>
    <hr />
{% endfor %}

{% endblock %}